sudo: required
services:
  - docker

before_install:
  - docker build -t dideex/react-test -f ./client/Dockerfile.dev ./client

script:
  # Start docker development stage and test it
  - docker run dideex/react-test npm test -- --coverage

after_success:
  - docker build -t dideex/complex-client ./client
  - docker build -t dideex/complex-nginx ./nginx
  - docker build -t dideex/complex-server ./server
  - docker build -t dideex/complex-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stding
  # Take those images and push them to docker hub
  - docker push dideex/complex-client
  - docker push dideex/complex-nginx
  - docker push dideex/complex-server
  - docker push dideex/complex-worker